---
title: "New Relic Log Integration for OCI"
description: >
  Forward logs from OCI Log Groups to New Relic using OCI Functions
  and Service Connector Hub
schemaVersion: 1.1.0
version: "1.0.0"
locale: "en"

variableGroups:
  - title: "OCI Configuration"
    visible: true
    variables:
      - tenancy_ocid
      - current_user_ocid
      - region

  - title: "New Relic Environment Configuration"
    visible: true
    variables:
      - newrelic_logging_endpoint
      - newrelic_api_key
      - newrelic_account_id

  - title: "Resource Configuration"
    visible: true
    variables:
      - dynamic_group_name
      - newrelic_logging_policy
      - newrelic_function_app
      - connector_hub_name
      - function_app_shape

variables:
  tenancy_ocid:
    type: string
    title: "Tenancy OCID"
    description: "OCI tenant OCID, more details can be found at https://docs.cloud.oracle.com/en-us/iaas/Content/API/Concepts/apisigningkey.htm#five"
    required: true
    visible: false

  current_user_ocid:
    type: string
    title: "User OCID"
    description: "The OCID of the current user executing the terraform script. Do not modify."
    required: true
    visible: false

  region:
    type: string
    title: "Region"
    description: "OCI Region as documented at https://docs.cloud.oracle.com/en-us/iaas/Content/General/Concepts/regions.htm"
    required: true
    visible: false

  dynamic_group_name:
    type: string
    title: "New Relic Dynamic Group Name"
    description: "The name of the dynamic group for giving access to service connector"
    required: true
    default: "newrelic-logging-dynamic-group"

  newrelic_logging_policy:
    type: string
    title: "New Relic Logging Policy"
    description: "The name of the policy for logging"
    required: true
    default: "newrelic-logging-policy"

  newrelic_logging_endpoint:
    type: enum
    title: "New Relic Logging Endpoint"
    description: "The endpoint to hit for sending the logs. Varies by region [US|EU]"
    required: true
    default: "https://log-api.newrelic.com/log/v1"
    enum:
      - "https://log-api.newrelic.com/log/v1"
      - "https://log-api.eu.newrelic.com/log/v1"

  newrelic_api_key:
    type: password
    title: "New Relic API Key"
    description: "The Ingest API key for sending logs to New Relic endpoints"
    required: true
    sensitive: true

  newrelic_account_id:
    type: string
    title: "New Relic Account ID"
    description: "The New Relic account ID for sending logging to New Relic endpoints"
    required: true
    sensitive: true
    confirmation: true

  newrelic_function_app:
    type: string
    title: "New Relic Function App Name"
    description: "The name of the function application"
    required: true
    default: "newrelic-logging-function-app"

  connector_hub_name:
    type: string
    title: "New Relic Connector Hub Name"
    description: "The prefix for the name of all of the resources"
    required: true
    default: "newrelic-logging-connector-hub"

  function_app_shape:
    type: enum
    title: "Function App Shape"
    description: "The shape of the function application. The docker image should be built accordingly. Use ARM if using Oracle Resource Manager stack"
    required: true
    default: "GENERIC_X86"
    visible: false
    enum:
      - "GENERIC_X86"
      - "GENERIC_ARM"

  log_sources:
    type: string
    title: "Log Sources (JSON Array)"
    description: "Enter a JSON string array of log sources. Example: [{\"compartment_name\":\"Comp1\",\"log_group_name\":\"Group1\",\"log_name\":\"Log1\"},{\"compartment_name\":\"Comp2\",\"log_group_name\":\"Group2\",\"log_name\":\"Log2\"}]"
    required: true