name: Terraform Zip and Semantic Release

on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  zip-and-semantic-release:
    runs-on: ubuntu-latest
    env:
      GIT_AUTHOR_EMAIL: opensource+bot@newrelic.com
      GIT_AUTHOR_NAME: New Relic OpenSource Bot
      GIT_COMMITTER_EMAIL: opensource+bot@newrelic.com
      GIT_COMMITTER_NAME: New Relic OpenSource Bot

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --no-save semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github

      - name: Zip terraform folder
        run: |
          zip -r oci-log-integration.zip terraform

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release

      - name: Upload Terraform zip to latest release
        uses: softprops/action-gh-release@v2
        if: success()
        with:
          files: oci-log-integration.zip
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}