name: Build and Deploy OCI Go Function Image

on:
  push:
    branches:
      - main
    paths:
      - 'logs-function/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'logs-function/**'
  workflow_dispatch:

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    environment:
      name: build-test-env
    steps:

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set permissions for build script
        run: chmod +x scripts/build_image.sh

      - name: Build Docker Image
        run: ./scripts/build_image.sh

  push_docker_image:
    runs-on: ubuntu-latest
    needs: build_docker_image
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    strategy:
      matrix:
        region:
          - us-ashburn-1
          - us-phoenix-1
    steps:

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set permissions for build script
        run: chmod +x scripts/build_and_push_image.sh

      - name: Push Docker Image to ${{ matrix.region }}
        run: ./scripts/build_and_push_image.sh ${{ matrix.region }}
        env:
          ORACLE_AUTH_TOKEN: ${{ secrets.ORACLE_AUTH_TOKEN }}
          OCI_REGION: ${{ matrix.region }}
          OCI_TENANCY_NAMESPACE: ${{ secrets.OCI_TENANCY_NAMESPACE }}
          OCI_USERNAME: ${{ secrets.OCI_USERNAME }}