name: 'Trivy Security Scans'

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  trivy_fs_scan:
    name: Trivy Filesystem Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required to upload SARIF results

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
          format: 'sarif'
          output: 'trivy-fs-results.sarif'

      - name: Upload Trivy filesystem results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-fs-results.sarif'

  trivy_image_scan:
    name: Trivy Docker Image Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required to upload SARIF results

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and load Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./logs-function
          file: ./logs-function/Dockerfile
          load: true
          tags: oci-log-integration-scan:latest

      - name: Run Trivy image scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'oci-log-integration-scan:latest'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
          format: 'sarif'
          output: 'trivy-image-results.sarif'

      - name: Upload Trivy image results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-image-results.sarif'