name: 'Simplified Trivy Scan'

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  trivy:
    name: Trivy security scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and load Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./logs-function
          file: ./logs-function/Dockerfile
          load: true
          tags: oci-log-integration-scan:latest
      
      - name: Run Trivy filesystem scan
        continue-on-error: true
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-fs-results.sarif'

      - name: Run Trivy image scan
        continue-on-error: true
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'oci-log-integration-scan:latest'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-image-results.sarif'
          
      - name: Upload Trivy filesystem results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-fs-results.sarif'

      - name: Upload Trivy image results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-image-results.sarif'