name: 'Repo Level Trivy Scan'

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  trivy:
    name: Trivy security scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image for scanning
        uses: docker/build-push-action@v6
        with:
          context: ./logs-function
          file: ./logs-function/Dockerfile
          load: true
          push: false
          tags: oci-log-integration-scan:latest
      
      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-fs-results.sarif'
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
          TRIVY_GO_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-go-db

      - name: Run Trivy image scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'oci-log-integration-scan:latest'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-image-results.sarif'
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
          TRIVY_GO_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-go-db

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: |
            trivy-fs-results.sarif
            trivy-image-results.sarif