name: 'Repo Level Trivy Scan'

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # 1st Job -- Build Docker Image and Push to GHCR
  build:
    name: 'Build and Push Docker Image'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    outputs:
      image-name: ${{ steps.set-image-name.outputs.image-name }}

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Log in to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push Docker image'
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: ./logs-function
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
          # Path to the Dockerfile
          file: ./logs-function/Dockerfile

      - name: 'Set image name output'
        id: set-image-name
        run: echo "image-name=ghcr.io/${{ github.repository }}:${{ github.sha }}" >> $GITHUB_OUTPUT

  # 2nd Job -- Call the reusable organization workflow for scanning
  scan:
    name: 'Trigger Organization Scan'
    needs: build
    permissions:
      contents: read
      packages: read
      security-events: write
      actions: write
      id-token: write    
      checks: write 
    uses: newrelic-trivy/.github/.github/workflows/org-level-trivy-scan.yml@main
    with:
      image-name: ${{ needs.build.outputs.image-name }}
    secrets: inherit